package main

import (
	"container/list"
	"fmt"
	"log"
	"mapreduce"
	"os"
	"strconv"
	"strings"
	"unicode"
)

// our simplified version of MapReduce does not supply a
// key to the Map function, as in the paper; only a value,
// which is a part of the input file content. the return
// value should be a list of key/value pairs, each represented
// by a mapreduce.KeyValue.
func Map(value string) *list.List {
	// for each word in value, count and store in list
	l := list.New()
	words := strings.FieldsFunc(string(value), isString)
	for i := 0; i < len(words); i++ {
		temp := new(mapreduce.KeyValue)
		temp.Key = words[i]
		temp.Value = "1"
		l.PushBack(*temp)
	}
	return l
}

// called once for each key generated by Map, with a list
// of that key's string value. should return a single
// output value for that key.
func Reduce(key string, values *list.List) string {
	// sum up all value with the given key
	sum := 0
	for e := values.Front(); e != nil; e = e.Next() {
		n, err := strconv.Atoi(e.Value.(string))
		//fmt.Println(key + ": " + e.Value.(string))
		if err != nil {
			log.Fatal("error parsing value")
			return "0"
		}
		sum += n
	}
	return strconv.Itoa(sum)
}

func isString(r rune) bool {
	return !unicode.IsLetter(r)
}

// Can be run in 3 ways:
// 1) Sequential (e.g., go run wc.go master x.txt sequential)
// 2) Master (e.g., go run wc.go master x.txt localhost:7777)
// 3) Worker (e.g., go run wc.go worker localhost:7777 localhost:7778 &)
func main() {
	if len(os.Args) != 4 {
		fmt.Printf("%s: see usage comments in file\n", os.Args[0])
	} else if os.Args[1] == "master" {
		if os.Args[3] == "sequential" {
			mapreduce.RunSingle(5, 3, os.Args[2], Map, Reduce)
		} else {
			mr := mapreduce.MakeMapReduce(5, 3, os.Args[2], os.Args[3])
			// Wait until MR is done
			<-mr.DoneChannel
		}
	} else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], Map, Reduce, 100)
	}
}
